name: $(Date:yyyyMMdd).$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  # batch: true
  branches:
    include:
    - master
    - development
    - feature/*

pr:
  branches:
    include:
    - master
    - development

variables:
  imageName: 'python-ci-cd-azure'
  major: 1
  minor: 2
  patch: 0 # $(Build.BuildId)

steps:

- checkout: self
  persistCredentials: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    architecture: 'x64'

- script: |
    pip install --upgrade pip setuptools wheel unittest-xml-reporting && cat azure-pipelines.yml
  displayName: 'Environment Preperation'

- script: |
    set -e
    cd ./IntegrationPackage
    python -m xmlrunner discover
    cd ../
  condition: succeeded()
  displayName: 'Testing Integration Package'

- script: |
    set -e
    cd ./IntegrationPackage
    python integration_setup.py sdist bdist_wheel
    cd ../
  condition: succeeded()
  displayName: 'Packaging Integration'

- script: |
    cd ./IntegrationPackage
    pip install dist/Integration-*3*.whl
    cd ../
  displayName: 'Installing Integration Package'

- script: |
    set -e
    cd ./WrapperPackage
    python -m xmlrunner discover
    cd ../
  condition: succeeded()
  displayName: 'Testing Wrapper Package'

- script: |
    set -e
    cd ./WrapperPackage
    python wrapper_setup.py sdist bdist_wheel
    cd ../
  condition: succeeded()
  displayName: 'Packaging Wrapper'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'

- script: |
    docker build -t $(dockerId)/$(imageName):$(major).$(minor).$(patch) .
  displayName: 'Build Docker image'

- script: |
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName):$(major).$(minor).$(patch)
    docker tag $(dockerId)/$(imageName):$(major).$(minor).$(patch) $(dockerId)/$(imageName):latest
    docker push $(dockerId)/$(imageName):latest
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  env:
    pswd: $(dockerPassword)
  displayName: 'Push Docker image'

- script: |
    git config --global user.email "reddy.horcrux@gmail.com"
    git config --global user.name "Sangram Reddy"
    git tag -a $(major).$(minor).$(patch) -m " v$(major).$(minor).$(patch)"
    git push origin $(major).$(minor).$(patch)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Tagging the build'

- script: |
    pip list
  displayName: 'Verification'
