pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'python-ci-cd-azure:$(Build.BuildId)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    architecture: 'x64'

- script: |
    ls -ltrha && pip install --upgrade pip setuptools wheel
  displayName: 'Environment Preperation'

- script: |
    cd ./IntegrationPackage
    python -m unittest discover
    cd ../
  displayName: 'Testing Integration Package'

- script: |
    cd ./IntegrationPackage
    python integration_setup.py sdist bdist_wheel
    cd ../
  displayName: 'Packaging Integration'

- script: |
    cd ./IntegrationPackage
    pip install dist/Integration-*3*.whl
    cd ../
  displayName: 'Installing Integration Package'

- script: |
    cd ./WrapperPackage
    python -m unittest discover
    cd ../
  displayName: 'Testing Wrapper Package'

- script: |
    cd ./WrapperPackage
    python wrapper_setup.py sdist bdist_wheel
    cd ../
  displayName: 'Packaging Wrapper'

- script: |
    docker build -t $(imageName) .
  displayName: 'Build Image'

- script: |
    pip list
  displayName: 'Verification'
