pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'python-ci-cd-azure:$(Build.BuildId)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    architecture: 'x64'

- script: |
    ls -ltrha && pip install --upgrade pip setuptools wheel

- script: |
    cd ./IntegrationPackage
    python -m unittest discover
    cd ../

- script: |
    cd ./IntegrationPackage
    python integration_setup.py sdist bdist_wheel
    cd ../

- script: |
    cd ./IntegrationPackage
    pip install dist/Integration-*3*.whl
    cd ../

- script: |
    pip list
  displayName: 'Verification'
