pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'python-ci-cd-azure:$(Build.BuildId)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Setup Environment'
  inputs:
    scriptSource: 'inline'
    script: |
    ls -ltrha
    python -m pip install --upgrade pip setuptools wheel

- task: PythonScript@0
  displayName: 'Test Integration Package'
  inputs:
    scriptSource: 'inline'
    script: |
    cd ./IntegrationPackage
    python -m unittest discover
    cd ../

- task: PythonScript@0
  displayName: 'Package Integration'
  inputs:
    scriptSource: 'inline'
    script: |
    cd ./IntegrationPackage
    python integration_setup.py sdist bdist_wheel
    cd ../

- script: |
    cd ./IntegrationPackage
    python -m pip install dist/Integration-*3*.whl
    cd ../
  displayName: 'Install Integration Locally'

- script: |
    pip list
  displayName: 'Verification'